require('dotenv').config()

const SHA512 = 'sha512'
const SHA256 = 'sha256'
const SHA1 = 'sha1'
const IDIOT_LUGGAGE_SECRET = '12345'  // DEFAULT IS INSECURE!
const HEX = 'hex'
const DEFAULT_MATCH_LENGTH = 0 // DEFAULT PERFORMS NO VALIDATION!
const DEFAULT_CHAIN_WEIGHT = 0 // DEFAULT DOES NOT GROW WITH CHAIN LENGTH!
const DEFAULT_REQUIRE_PROOF = false // DEFAULT PERFORMS NO VALIDATION!
const DEFAULT_ADVANCE_BLOCK = false // DEFAULT DOES NOT ADVANCE HASH TARGET BLOCK!
const DEFAULT_ZERO_NODE = '0'
const DEFAULT_GENESIS_DATA = 'Genesis Block'
const {
  CRYPTO_SECRET = IDIOT_LUGGAGE_SECRET,
  HASH_TYPE = SHA256,
  DIGEST = HEX,
  PROOF_SEED = IDIOT_LUGGAGE_SECRET,
  RESOLUTION_MATCH_LENGTH = DEFAULT_MATCH_LENGTH,
  RESOLUTION_CHAIN_WEIGHT = DEFAULT_CHAIN_WEIGHT,
  REQUIRE_PROOF = DEFAULT_REQUIRE_PROOF,
  ADVANCE_BLOCK = DEFAULT_ADVANCE_BLOCK,
  ZERO_NODE_ADDRESS = DEFAULT_ZERO_NODE,
  GENESIS_PROOF = IDIOT_LUGGAGE_SECRET,
  GENESIS_DATA = DEFAULT_GENESIS_DATA
} = process.env

module.exports = {
  CRYPTO_SECRET,
  HASH_TYPE,
  DIGEST,
  HASH_TYPES: {
    SHA1,
    SHA256,
    SHA512
  },
  DIGEST_TYPES: {
    HEX
  },
  PROOF_SEED,
  REQUIRE_PROOF: REQUIRE_PROOF === 'true' || Number(REQUIRE_PROOF) ? true : false,
  RESOLUTION_MATCH_LENGTH,
  RESOLUTION_CHAIN_WEIGHT,
  ADVANCE_BLOCK,
  ZERO_NODE_ADDRESS,
  GENESIS_PROOF,
  GENESIS_DATA,
}
